[package]
name = "nectar-primitives-new"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
## nectar
nectar-access-control.workspace = true

## crypt
alloy-primitives.workspace = true
digest.workspace = true
generic-array.workspace = true

# concurrency and parallelism
rayon.workspace = true

# Core dependencies
bytes.workspace = true
thiserror.workspace = true
once_cell.workspace = true

# Trait helpers
auto_impl.workspace = true
dyn-clone.workspace = true

[dev-dependencies]
# For examples
alloy-primitives.workspace = true
# For benchmarks
criterion.workspace = true
tokio.workspace = true
rand.workspace = true

[[bench]]
name = "primitives"
harness = false

[[bench]]
name = "proofs"
harness = false
