[package]
name = "vertex-node"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
description = "Vertex Swarm node executable"

[dependencies]
# Internal dependencies
vertex-primitives = { workspace = true }
vertex-swarm-api = { workspace = true }
vertex-swarmspec = { workspace = true }
vertex-node-api = { workspace = true }
vertex-storage = { workspace = true }
vertex-network = { workspace = true }
vertex-access = { workspace = true }
vertex-protocol = { workspace = true }
vertex-bandwidth = { workspace = true }
vertex-api = { workspace = true }
vertex-metrics = { workspace = true }

# CLI
clap = { version = "4.3", features = ["derive", "env"] }
directories = "5.0"
shellexpand = "3.1"

# Tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"

# Async runtime
tokio = { version = "1.29", features = ["full", "tracing"] }
futures = "0.3"

# Error handling
eyre = "0.6"
color-eyre = "0.6"

# Misc
once_cell = "1.17"
humantime = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.7"
chrono = "0.4"
rand = "0.8"
hex = "0.4"

[build-dependencies]
vergen = { version = "7.0", features = ["build", "git", "gitcl"] }

[[bin]]
name = "vertex"
path = "src/main.rs"
