//! Fuzz-facing surface behind the `arbitrary` feature: the invariant sweeps
//! for the trimmed big-endian `U256` wire helpers and the uvarint
//! length-delimited frame layer, shared between the fuzz targets and the
//! stable seed-replay tests. Dev-only; never enabled by a shipped artefact
//! cone.

use std::convert::Infallible;

use alloy_primitives::U256;
use asynchronous_codec::{Decoder, Encoder};
use bytes::BytesMut;
use quick_protobuf::{BytesReader, MessageRead, MessageWrite, Writer, WriterBackend};

use crate::utils::{U256DecodeError, decode_u256_be, encode_u256_be};
use crate::{Codec, FramedProto, ProtoMessage, StreamClosed};

/// Run the `u256_wire` invariant sweep over one raw input.
///
/// Decode must be the exact inverse of encode: an accepted input re-encodes
/// to the identical bytes, a rejected input is provably non-canonical
/// (oversized or leading-zero), and any 32-byte prefix taken as a value
/// round-trips through encode then decode. A violation panics.
pub fn check_u256_wire(data: &[u8]) {
    match decode_u256_be(data) {
        Ok(value) => assert_eq!(
            encode_u256_be(value).as_slice(),
            data,
            "an accepted input must re-encode to the identical bytes"
        ),
        Err(U256DecodeError::Oversized(len)) => {
            assert_eq!(len, data.len());
            assert!(len > 32, "oversized rejection requires more than 32 bytes");
        }
        Err(U256DecodeError::LeadingZero) => assert_eq!(
            data.first(),
            Some(&0),
            "leading-zero rejection requires a leading zero byte"
        ),
    }

    if let Some(prefix) = data.first_chunk::<32>() {
        let value = U256::from_be_bytes(*prefix);
        assert_eq!(
            decode_u256_be(&encode_u256_be(value)),
            Ok(value),
            "decode(encode(x)) must reproduce the value"
        );
    }
}

const CAP_PAGE_REQUEST: usize = 80;
const CAP_CONTROL: usize = 1024;
const CAP_CHEQUE: usize = 4096;
const CAP_CHUNK_DELIVERY: usize = 4410;
const CAP_PEER_BATCH: usize = 32 * 1024;

/// Frame-size caps mirroring the per-protocol budgets, from the smallest
/// fixed-shape request through the control frames, cheque and chunk-delivery
/// frames, up to the peer-gossip batch. Coverage matrix only; the binding
/// constants live in each protocol crate.
pub const FRAME_CAPS: [usize; 5] = [
    CAP_PAGE_REQUEST,
    CAP_CONTROL,
    CAP_CHEQUE,
    CAP_CHUNK_DELIVERY,
    CAP_PEER_BATCH,
];

/// Opaque frame payload: the write emits the raw bytes and the read accepts
/// any payload, so the sweep isolates the length-prefix layer from
/// per-message validation.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct RawFrame(pub Vec<u8>);

impl MessageWrite for RawFrame {
    fn write_message<W: WriterBackend>(&self, w: &mut Writer<W>) -> quick_protobuf::Result<()> {
        for &byte in &self.0 {
            w.write_u8(byte)?;
        }
        Ok(())
    }

    fn get_size(&self) -> usize {
        self.0.len()
    }
}

impl<'a> MessageRead<'a> for RawFrame {
    fn from_reader(r: &mut BytesReader, bytes: &'a [u8]) -> quick_protobuf::Result<Self> {
        let mut payload = Vec::with_capacity(bytes.len());
        while !r.is_eof() {
            payload.push(r.read_u8(bytes)?);
        }
        Ok(Self(payload))
    }
}

impl ProtoMessage for RawFrame {
    type Proto = Self;
    type EncodeError = Infallible;
    type DecodeError = Infallible;

    fn into_proto(self) -> Result<Self::Proto, Self::EncodeError> {
        Ok(self)
    }

    fn from_proto(proto: Self::Proto) -> Result<Self, Self::DecodeError> {
        Ok(proto)
    }
}

crate::protocol_error! {
    /// Error for the framing sweep, generated by [`protocol_error!`] so the
    /// sweep pins the macro's error mapping alongside the frame layer.
    pub enum FramingError {}
}

impl From<StreamClosed> for FramingError {
    fn from(_: StreamClosed) -> Self {
        Self::ConnectionClosed
    }
}

type FramingCodec = Codec<RawFrame, FramingError>;

/// Run the `framing_decode` invariant sweep over one raw input.
///
/// The first byte selects the feed chunk size; the rest is the byte stream.
/// Across every cap in [`FRAME_CAPS`] the sweep asserts: chunk boundaries
/// never change the decoded frames, a wait consumes nothing, a declared
/// length above the cap is rejected on the bare prefix before any payload
/// arrives, a cap-sized frame decodes while one byte over is refused, a
/// valid frame decodes intact regardless of trailing garbage and consumes
/// exactly its own bytes, every yielded frame survives
/// decode-encode-decode, and [`FramedProto`] agrees with the raw decoder.
/// A violation panics.
pub fn check_framing(data: &[u8]) {
    let Some((&ctrl, stream)) = data.split_first() else {
        return;
    };
    let chunk = usize::from(ctrl) + 1;

    for cap in FRAME_CAPS {
        let chunked = drive(stream, cap, chunk);
        let oneshot = decode_all(stream, cap);
        assert_eq!(
            chunked, oneshot,
            "chunk boundaries must not change the decoded frames"
        );

        check_prefix_rejection(stream, cap);
        check_cap_boundary(stream, cap);
        check_frame_then_garbage(stream, cap);
    }

    check_framed_recv::<CAP_PAGE_REQUEST>(stream);
    check_framed_recv::<CAP_CONTROL>(stream);
    check_framed_recv::<CAP_CHEQUE>(stream);
    check_framed_recv::<CAP_CHUNK_DELIVERY>(stream);
    check_framed_recv::<CAP_PEER_BATCH>(stream);
}

/// Decode every frame in `stream` at `cap` in a single feed. The second
/// element is `true` when the decoder errored.
pub fn decode_all(stream: &[u8], cap: usize) -> (Vec<RawFrame>, bool) {
    drive(stream, cap, stream.len().max(1))
}

/// Feed `stream` into the decoder `chunk` bytes at a time, asserting the
/// per-step invariants: a yielded frame respects the cap and survives
/// decode-encode-decode, a wait consumes nothing, and a failure surfaces as
/// the protobuf-mapped variant.
fn drive(stream: &[u8], cap: usize, chunk: usize) -> (Vec<RawFrame>, bool) {
    let mut codec = FramingCodec::new(cap);
    let mut src = BytesMut::new();
    let mut frames = Vec::new();

    for piece in stream.chunks(chunk) {
        src.extend_from_slice(piece);
        loop {
            let before = src.len();
            match codec.decode(&mut src) {
                Ok(Some(frame)) => {
                    assert!(frame.0.len() <= cap, "a yielded frame must respect the cap");
                    check_reencode(&mut codec, &frame);
                    frames.push(frame);
                }
                Ok(None) => {
                    assert_eq!(src.len(), before, "a wait must not consume bytes");
                    break;
                }
                Err(error) => {
                    assert!(
                        matches!(error, FramingError::Protobuf(_)),
                        "a frame-layer failure must map to the protobuf variant"
                    );
                    return (frames, true);
                }
            }
        }
    }

    (frames, false)
}

/// Decode-encode-decode stability: a yielded frame re-encodes into exactly
/// one frame that decodes back equal.
fn check_reencode(codec: &mut FramingCodec, frame: &RawFrame) {
    let mut buf = BytesMut::new();
    encode_frame(codec, frame.clone(), &mut buf);
    match codec.decode(&mut buf) {
        Ok(Some(redecoded)) => {
            assert_eq!(&redecoded, frame, "decode-encode-decode must be stable");
            assert!(buf.is_empty(), "a re-encoded frame must decode in one step");
        }
        other => panic!("a re-encoded frame must decode completely, got {other:?}"),
    }
}

/// A declared length above the cap must be rejected on the bare length
/// prefix, before a single payload byte arrives, so a short prefix can
/// never reserve unbounded memory.
fn check_prefix_rejection(stream: &[u8], cap: usize) {
    let mut seed = [0u8; 8];
    for (dst, src) in seed.iter_mut().zip(stream) {
        *dst = *src;
    }
    let declared = u64::from_le_bytes(seed).max(cap as u64 + 1);

    let mut codec = FramingCodec::new(cap);
    let mut src = BytesMut::from(uvarint(declared).as_slice());
    assert!(
        matches!(codec.decode(&mut src), Err(FramingError::Protobuf(_))),
        "a declared length above the cap must be rejected before any payload"
    );
}

/// A frame of exactly `cap` bytes decodes (fed across a split), one byte
/// over is refused.
fn check_cap_boundary(stream: &[u8], cap: usize) {
    let mut codec = FramingCodec::new(cap);

    let mut payload = vec![0u8; cap];
    for (dst, src) in payload.iter_mut().zip(stream.iter().cycle()) {
        *dst = *src;
    }
    let frame = RawFrame(payload);

    let mut wire = BytesMut::new();
    encode_frame(&mut codec, frame.clone(), &mut wire);
    let (head, tail) = wire.split_at(wire.len() / 2);

    let mut src = BytesMut::from(head);
    assert!(
        matches!(codec.decode(&mut src), Ok(None)),
        "half a cap-sized frame must wait for more bytes"
    );
    src.extend_from_slice(tail);
    match codec.decode(&mut src) {
        Ok(Some(got)) => assert_eq!(got, frame, "a cap-sized frame must decode intact"),
        other => panic!("a cap-sized frame must decode, got {other:?}"),
    }
    assert!(src.is_empty(), "a cap-sized frame must consume its bytes");

    let mut wire = BytesMut::new();
    encode_frame(&mut codec, RawFrame(vec![0u8; cap + 1]), &mut wire);
    assert!(
        matches!(codec.decode(&mut wire), Err(FramingError::Protobuf(_))),
        "one byte over the cap must be refused"
    );
}

/// Garbage after a valid frame must not corrupt it: the frame decodes
/// intact and consumes exactly its own bytes, leaving the tail untouched
/// for the next decode.
fn check_frame_then_garbage(stream: &[u8], cap: usize) {
    let mut codec = FramingCodec::new(cap);
    let frame = RawFrame(stream.iter().copied().take(cap).collect());

    let mut src = BytesMut::new();
    encode_frame(&mut codec, frame.clone(), &mut src);
    src.extend_from_slice(stream);

    match codec.decode(&mut src) {
        Ok(Some(got)) => assert_eq!(
            got, frame,
            "trailing garbage must not corrupt a valid frame"
        ),
        other => panic!("a valid frame ahead of garbage must decode, got {other:?}"),
    }
    assert_eq!(
        src.as_ref(),
        stream,
        "a decoded frame must consume exactly its own bytes"
    );
}

/// [`FramedProto`] over the same bytes must agree with the raw decoder:
/// same first frame, a clean end of stream maps through [`StreamClosed`],
/// and a truncated or malformed stream surfaces as a codec error.
fn check_framed_recv<const BUF: usize>(stream: &[u8]) {
    let mut codec = FramingCodec::new(BUF);
    let mut src = BytesMut::from(stream);
    let direct = codec.decode(&mut src);

    let recvd = futures::executor::block_on(FramedProto::<BUF>::recv::<RawFrame, FramingError, _>(
        futures::io::Cursor::new(stream.to_vec()),
    ));

    match (direct, recvd) {
        (Ok(Some(frame)), Ok((msg, _))) => assert_eq!(
            msg, frame,
            "recv must yield the same first frame as the raw decoder"
        ),
        (Ok(None), Err(FramingError::ConnectionClosed)) => assert!(
            stream.is_empty(),
            "the closed mapping is reserved for a clean end of stream"
        ),
        (Ok(None), Err(FramingError::Protobuf(_))) => assert!(
            !stream.is_empty(),
            "a truncated tail must surface as a codec error"
        ),
        (Err(_), Err(FramingError::Protobuf(_))) => {}
        (direct, recvd) => {
            panic!("framed recv diverged from the raw decoder: {direct:?} vs {recvd:?}")
        }
    }
}

/// Encode `frame` into `dst`; a raw frame write cannot fail.
fn encode_frame(codec: &mut FramingCodec, frame: RawFrame, dst: &mut BytesMut) {
    codec
        .encode(frame, dst)
        .unwrap_or_else(|error| panic!("a raw frame encode is total: {error}"));
}

/// Minimal unsigned-varint encoding of `value`.
fn uvarint(mut value: u64) -> Vec<u8> {
    let mut out = Vec::with_capacity(10);
    loop {
        let byte = (value & 0x7f) as u8;
        value >>= 7;
        if value == 0 {
            out.push(byte);
            return out;
        }
        out.push(byte | 0x80);
    }
}
