[package]
name = "vertex-storage"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
description = "Storage implementations for Vertex Swarm"

[dependencies]
# Internal crates
vertex-primitives = { workspace = true }
vertex-swarm-api = { workspace = true }

# Async
tokio = { version = "1.28", features = ["full"] }
async-trait = "0.1"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"

# Logging
tracing = "0.1"

# Database/Storage
rocksdb = { version = "0.20", optional = true }
sled = { version = "0.34", optional = true }

# Misc
auto_impl = "1.1"
dashmap = "5.4"
bytes = "1.4"
thiserror = "1.0"

[features]
default = ["rocksdb"]
rocksdb = ["dep:rocksdb"]
sled = ["dep:sled"]
