[package]
name = "vertex-primitives"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
description = "Core primitive types for the Vertex Swarm node"

[dependencies]
# Serialization
serde = { version = "1.0", features = ["derive"], optional = true }
# Crypto
sha3 = "0.10"
hex = "0.4"
# Error handling
thiserror = "1.0"
# Additional
auto_impl = "1.1"

[features]
default = ["std", "serde"]
std = ["serde?/std"]
serde = ["dep:serde"]
