[package]
name = "vertex-swarmspec"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
description = "Swarm network specification for Vertex"

[dependencies]
# Internal crates
vertex-primitives = { workspace = true }

# Network
libp2p = { version = "0.52", features = ["identify", "kad", "ping", "noise"] }

# Serialization
serde = { version = "1.0", features = ["derive"], optional = true }

# Error handling
thiserror = "1.0"

# Misc
once_cell = "1.17"
tracing = "0.1"
auto_impl = "1.1"

[features]
default = ["std", "serde"]
std = ["vertex-primitives/std", "serde?/std"]
serde = ["dep:serde", "vertex-primitives/serde"]
