// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/client.dart';
import 'api/error.dart';
import 'api/logging.dart';
import 'api/metrics.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1948237842;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'vertex_ffi',
    ioDirectory: '../../target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<VertexClient> crateApiClientVertexClientBuild(
      {required VertexClientConfig config});

  Future<VertexChunkDownload> crateApiClientVertexClientDownloadChunk(
      {required VertexClient that,
      required List<int> address,
      required bool verifyStamp});

  Stream<VertexChunkData> crateApiClientVertexClientDownloadStream(
      {required VertexClient that,
      required List<Uint8List> addresses,
      required VertexStreamConfig config});

  Future<VertexPushReceipt> crateApiClientVertexClientUploadChunk(
      {required VertexClient that, required VertexChunkUpload chunk});

  Stream<VertexUploadAck> crateApiClientVertexClientUploadStream(
      {required VertexClient that,
      required List<VertexChunkUpload> chunks,
      required VertexStreamConfig config});

  Stream<LogLine> crateApiLoggingInitLogging({required String level});

  Future<void> crateApiMetricsInitMetrics();

  Future<MetricsSnapshot> crateApiMetricsMetricsSnapshot();

  Future<VertexClientConfig> crateApiTypesVertexClientConfigDefault();

  Future<VertexNetwork> crateApiTypesVertexNetworkDefault();

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_VertexClient;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_VertexClient;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_VertexClientPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<VertexClient> crateApiClientVertexClientBuild(
      {required VertexClientConfig config}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_vertex_client_config(config, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVertexClient,
        decodeErrorData: sse_decode_ffi_error,
      ),
      constMeta: kCrateApiClientVertexClientBuildConstMeta,
      argValues: [config],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiClientVertexClientBuildConstMeta =>
      const TaskConstMeta(
        debugName: "VertexClient_build",
        argNames: ["config"],
      );

  @override
  Future<VertexChunkDownload> crateApiClientVertexClientDownloadChunk(
      {required VertexClient that,
      required List<int> address,
      required bool verifyStamp}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVertexClient(
            that, serializer);
        sse_encode_list_prim_u_8_loose(address, serializer);
        sse_encode_bool(verifyStamp, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_vertex_chunk_download,
        decodeErrorData: sse_decode_ffi_error,
      ),
      constMeta: kCrateApiClientVertexClientDownloadChunkConstMeta,
      argValues: [that, address, verifyStamp],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiClientVertexClientDownloadChunkConstMeta =>
      const TaskConstMeta(
        debugName: "VertexClient_download_chunk",
        argNames: ["that", "address", "verifyStamp"],
      );

  @override
  Stream<VertexChunkData> crateApiClientVertexClientDownloadStream(
      {required VertexClient that,
      required List<Uint8List> addresses,
      required VertexStreamConfig config}) {
    final sink = RustStreamSink<VertexChunkData>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVertexClient(
            that, serializer);
        sse_encode_list_list_prim_u_8_strict(addresses, serializer);
        sse_encode_box_autoadd_vertex_stream_config(config, serializer);
        sse_encode_StreamSink_vertex_chunk_data_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_ffi_error,
      ),
      constMeta: kCrateApiClientVertexClientDownloadStreamConstMeta,
      argValues: [that, addresses, config, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiClientVertexClientDownloadStreamConstMeta =>
      const TaskConstMeta(
        debugName: "VertexClient_download_stream",
        argNames: ["that", "addresses", "config", "sink"],
      );

  @override
  Future<VertexPushReceipt> crateApiClientVertexClientUploadChunk(
      {required VertexClient that, required VertexChunkUpload chunk}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVertexClient(
            that, serializer);
        sse_encode_box_autoadd_vertex_chunk_upload(chunk, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_vertex_push_receipt,
        decodeErrorData: sse_decode_ffi_error,
      ),
      constMeta: kCrateApiClientVertexClientUploadChunkConstMeta,
      argValues: [that, chunk],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiClientVertexClientUploadChunkConstMeta =>
      const TaskConstMeta(
        debugName: "VertexClient_upload_chunk",
        argNames: ["that", "chunk"],
      );

  @override
  Stream<VertexUploadAck> crateApiClientVertexClientUploadStream(
      {required VertexClient that,
      required List<VertexChunkUpload> chunks,
      required VertexStreamConfig config}) {
    final sink = RustStreamSink<VertexUploadAck>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVertexClient(
            that, serializer);
        sse_encode_list_vertex_chunk_upload(chunks, serializer);
        sse_encode_box_autoadd_vertex_stream_config(config, serializer);
        sse_encode_StreamSink_vertex_upload_ack_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_ffi_error,
      ),
      constMeta: kCrateApiClientVertexClientUploadStreamConstMeta,
      argValues: [that, chunks, config, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiClientVertexClientUploadStreamConstMeta =>
      const TaskConstMeta(
        debugName: "VertexClient_upload_stream",
        argNames: ["that", "chunks", "config", "sink"],
      );

  @override
  Stream<LogLine> crateApiLoggingInitLogging({required String level}) {
    final sink = RustStreamSink<LogLine>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(level, serializer);
        sse_encode_StreamSink_log_line_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_ffi_error,
      ),
      constMeta: kCrateApiLoggingInitLoggingConstMeta,
      argValues: [level, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiLoggingInitLoggingConstMeta => const TaskConstMeta(
        debugName: "init_logging",
        argNames: ["level", "sink"],
      );

  @override
  Future<void> crateApiMetricsInitMetrics() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_ffi_error,
      ),
      constMeta: kCrateApiMetricsInitMetricsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMetricsInitMetricsConstMeta => const TaskConstMeta(
        debugName: "init_metrics",
        argNames: [],
      );

  @override
  Future<MetricsSnapshot> crateApiMetricsMetricsSnapshot() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_metrics_snapshot,
        decodeErrorData: sse_decode_ffi_error,
      ),
      constMeta: kCrateApiMetricsMetricsSnapshotConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMetricsMetricsSnapshotConstMeta =>
      const TaskConstMeta(
        debugName: "metrics_snapshot",
        argNames: [],
      );

  @override
  Future<VertexClientConfig> crateApiTypesVertexClientConfigDefault() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_vertex_client_config,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiTypesVertexClientConfigDefaultConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTypesVertexClientConfigDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "vertex_client_config_default",
        argNames: [],
      );

  @override
  Future<VertexNetwork> crateApiTypesVertexNetworkDefault() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_vertex_network,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiTypesVertexNetworkDefaultConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTypesVertexNetworkDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "vertex_network_default",
        argNames: [],
      );

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_VertexClient => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVertexClient;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_VertexClient => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVertexClient;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  VertexClient
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVertexClient(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VertexClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  VertexClient
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVertexClient(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VertexClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  VertexClient
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVertexClient(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VertexClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<LogLine> dco_decode_StreamSink_log_line_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<VertexChunkData> dco_decode_StreamSink_vertex_chunk_data_Sse(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<VertexUploadAck> dco_decode_StreamSink_vertex_upload_ack_Sse(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  VertexChunkUpload dco_decode_box_autoadd_vertex_chunk_upload(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_vertex_chunk_upload(raw);
  }

  @protected
  VertexClientConfig dco_decode_box_autoadd_vertex_client_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_vertex_client_config(raw);
  }

  @protected
  VertexPushReceipt dco_decode_box_autoadd_vertex_push_receipt(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_vertex_push_receipt(raw);
  }

  @protected
  VertexStreamConfig dco_decode_box_autoadd_vertex_stream_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_vertex_stream_config(raw);
  }

  @protected
  CounterValue dco_decode_counter_value(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return CounterValue(
      name: dco_decode_String(arr[0]),
      labels: dco_decode_list_record_string_string(arr[1]),
      value: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FfiError dco_decode_ffi_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return FfiError_InvalidPrivateKey(
          len: dco_decode_usize(raw[1]),
        );
      case 1:
        return FfiError_InvalidAddress(
          len: dco_decode_usize(raw[1]),
        );
      case 2:
        return FfiError_InvalidStamp(
          reason: dco_decode_String(raw[1]),
        );
      case 3:
        return FfiError_ChunkMismatch(
          reason: dco_decode_String(raw[1]),
        );
      case 4:
        return FfiError_Build(
          reason: dco_decode_String(raw[1]),
        );
      case 5:
        return FfiError_Upload(
          reason: dco_decode_String(raw[1]),
        );
      case 6:
        return FfiError_Download(
          reason: dco_decode_String(raw[1]),
        );
      case 7:
        return FfiError_Logging(
          reason: dco_decode_String(raw[1]),
        );
      case 8:
        return FfiError_LoggingAlreadyInitialized();
      case 9:
        return FfiError_Metrics(
          reason: dco_decode_String(raw[1]),
        );
      case 10:
        return FfiError_MetricsAlreadyInitialized();
      case 11:
        return FfiError_MetricsNotInitialized();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  GaugeValue dco_decode_gauge_value(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return GaugeValue(
      name: dco_decode_String(arr[0]),
      labels: dco_decode_list_record_string_string(arr[1]),
      value: dco_decode_f_64(arr[2]),
    );
  }

  @protected
  HistogramValue dco_decode_histogram_value(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return HistogramValue(
      name: dco_decode_String(arr[0]),
      labels: dco_decode_list_record_string_string(arr[1]),
      count: dco_decode_u_64(arr[2]),
      sum: dco_decode_f_64(arr[3]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<CounterValue> dco_decode_list_counter_value(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_counter_value).toList();
  }

  @protected
  List<GaugeValue> dco_decode_list_gauge_value(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_gauge_value).toList();
  }

  @protected
  List<HistogramValue> dco_decode_list_histogram_value(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_histogram_value).toList();
  }

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_prim_u_8_strict).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_string).toList();
  }

  @protected
  List<VertexChunkUpload> dco_decode_list_vertex_chunk_upload(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_vertex_chunk_upload).toList();
  }

  @protected
  LogLevel dco_decode_log_level(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LogLevel.values[raw as int];
  }

  @protected
  LogLine dco_decode_log_line(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return LogLine(
      timestampMs: dco_decode_i_64(arr[0]),
      level: dco_decode_log_level(arr[1]),
      target: dco_decode_String(arr[2]),
      message: dco_decode_String(arr[3]),
      fields: dco_decode_list_record_string_string(arr[4]),
    );
  }

  @protected
  MetricsSnapshot dco_decode_metrics_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return MetricsSnapshot(
      timestampMs: dco_decode_i_64(arr[0]),
      counters: dco_decode_list_counter_value(arr[1]),
      gauges: dco_decode_list_gauge_value(arr[2]),
      histograms: dco_decode_list_histogram_value(arr[3]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  VertexPushReceipt? dco_decode_opt_box_autoadd_vertex_push_receipt(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_vertex_push_receipt(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_String(arr[0]),
      dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  VertexChunkData dco_decode_vertex_chunk_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return VertexChunkData(
      index: dco_decode_u_64(arr[0]),
      address: dco_decode_list_prim_u_8_strict(arr[1]),
      data: dco_decode_list_prim_u_8_strict(arr[2]),
      stamp: dco_decode_list_prim_u_8_strict(arr[3]),
      error: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  VertexChunkDownload dco_decode_vertex_chunk_download(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return VertexChunkDownload(
      data: dco_decode_list_prim_u_8_strict(arr[0]),
      stamp: dco_decode_list_prim_u_8_strict(arr[1]),
      servedBy: dco_decode_String(arr[2]),
    );
  }

  @protected
  VertexChunkUpload dco_decode_vertex_chunk_upload(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return VertexChunkUpload(
      address: dco_decode_list_prim_u_8_strict(arr[0]),
      data: dco_decode_list_prim_u_8_strict(arr[1]),
      stamp: dco_decode_list_prim_u_8_strict(arr[2]),
      validate: dco_decode_bool(arr[3]),
    );
  }

  @protected
  VertexClientConfig dco_decode_vertex_client_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return VertexClientConfig(
      network: dco_decode_vertex_network(arr[0]),
      privateKey: dco_decode_opt_list_prim_u_8_strict(arr[1]),
      bootnodes: dco_decode_list_String(arr[2]),
    );
  }

  @protected
  VertexNetwork dco_decode_vertex_network(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VertexNetwork.values[raw as int];
  }

  @protected
  VertexPushReceipt dco_decode_vertex_push_receipt(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return VertexPushReceipt(
      storer: dco_decode_String(arr[0]),
      signature: dco_decode_list_prim_u_8_strict(arr[1]),
      nonce: dco_decode_list_prim_u_8_strict(arr[2]),
      storageRadius: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  VertexStreamConfig dco_decode_vertex_stream_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return VertexStreamConfig(
      windowBytes: dco_decode_u_64(arr[0]),
      maxConcurrency: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  VertexUploadAck dco_decode_vertex_upload_ack(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return VertexUploadAck(
      index: dco_decode_u_64(arr[0]),
      address: dco_decode_list_prim_u_8_strict(arr[1]),
      receipt: dco_decode_opt_box_autoadd_vertex_push_receipt(arr[2]),
      error: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  VertexClient
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVertexClient(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VertexClientImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  VertexClient
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVertexClient(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VertexClientImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  VertexClient
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVertexClient(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VertexClientImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  RustStreamSink<LogLine> sse_decode_StreamSink_log_line_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<VertexChunkData> sse_decode_StreamSink_vertex_chunk_data_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<VertexUploadAck> sse_decode_StreamSink_vertex_upload_ack_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  VertexChunkUpload sse_decode_box_autoadd_vertex_chunk_upload(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_vertex_chunk_upload(deserializer));
  }

  @protected
  VertexClientConfig sse_decode_box_autoadd_vertex_client_config(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_vertex_client_config(deserializer));
  }

  @protected
  VertexPushReceipt sse_decode_box_autoadd_vertex_push_receipt(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_vertex_push_receipt(deserializer));
  }

  @protected
  VertexStreamConfig sse_decode_box_autoadd_vertex_stream_config(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_vertex_stream_config(deserializer));
  }

  @protected
  CounterValue sse_decode_counter_value(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_labels = sse_decode_list_record_string_string(deserializer);
    var var_value = sse_decode_u_64(deserializer);
    return CounterValue(name: var_name, labels: var_labels, value: var_value);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FfiError sse_decode_ffi_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_len = sse_decode_usize(deserializer);
        return FfiError_InvalidPrivateKey(len: var_len);
      case 1:
        var var_len = sse_decode_usize(deserializer);
        return FfiError_InvalidAddress(len: var_len);
      case 2:
        var var_reason = sse_decode_String(deserializer);
        return FfiError_InvalidStamp(reason: var_reason);
      case 3:
        var var_reason = sse_decode_String(deserializer);
        return FfiError_ChunkMismatch(reason: var_reason);
      case 4:
        var var_reason = sse_decode_String(deserializer);
        return FfiError_Build(reason: var_reason);
      case 5:
        var var_reason = sse_decode_String(deserializer);
        return FfiError_Upload(reason: var_reason);
      case 6:
        var var_reason = sse_decode_String(deserializer);
        return FfiError_Download(reason: var_reason);
      case 7:
        var var_reason = sse_decode_String(deserializer);
        return FfiError_Logging(reason: var_reason);
      case 8:
        return FfiError_LoggingAlreadyInitialized();
      case 9:
        var var_reason = sse_decode_String(deserializer);
        return FfiError_Metrics(reason: var_reason);
      case 10:
        return FfiError_MetricsAlreadyInitialized();
      case 11:
        return FfiError_MetricsNotInitialized();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  GaugeValue sse_decode_gauge_value(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_labels = sse_decode_list_record_string_string(deserializer);
    var var_value = sse_decode_f_64(deserializer);
    return GaugeValue(name: var_name, labels: var_labels, value: var_value);
  }

  @protected
  HistogramValue sse_decode_histogram_value(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_labels = sse_decode_list_record_string_string(deserializer);
    var var_count = sse_decode_u_64(deserializer);
    var var_sum = sse_decode_f_64(deserializer);
    return HistogramValue(
        name: var_name, labels: var_labels, count: var_count, sum: var_sum);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<CounterValue> sse_decode_list_counter_value(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CounterValue>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_counter_value(deserializer));
    }
    return ans_;
  }

  @protected
  List<GaugeValue> sse_decode_list_gauge_value(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <GaugeValue>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_gauge_value(deserializer));
    }
    return ans_;
  }

  @protected
  List<HistogramValue> sse_decode_list_histogram_value(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <HistogramValue>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_histogram_value(deserializer));
    }
    return ans_;
  }

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Uint8List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_u_8_strict(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  List<VertexChunkUpload> sse_decode_list_vertex_chunk_upload(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <VertexChunkUpload>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_vertex_chunk_upload(deserializer));
    }
    return ans_;
  }

  @protected
  LogLevel sse_decode_log_level(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return LogLevel.values[inner];
  }

  @protected
  LogLine sse_decode_log_line(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_timestampMs = sse_decode_i_64(deserializer);
    var var_level = sse_decode_log_level(deserializer);
    var var_target = sse_decode_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_fields = sse_decode_list_record_string_string(deserializer);
    return LogLine(
        timestampMs: var_timestampMs,
        level: var_level,
        target: var_target,
        message: var_message,
        fields: var_fields);
  }

  @protected
  MetricsSnapshot sse_decode_metrics_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_timestampMs = sse_decode_i_64(deserializer);
    var var_counters = sse_decode_list_counter_value(deserializer);
    var var_gauges = sse_decode_list_gauge_value(deserializer);
    var var_histograms = sse_decode_list_histogram_value(deserializer);
    return MetricsSnapshot(
        timestampMs: var_timestampMs,
        counters: var_counters,
        gauges: var_gauges,
        histograms: var_histograms);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  VertexPushReceipt? sse_decode_opt_box_autoadd_vertex_push_receipt(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_vertex_push_receipt(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (String, String) sse_decode_record_string_string(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  VertexChunkData sse_decode_vertex_chunk_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_index = sse_decode_u_64(deserializer);
    var var_address = sse_decode_list_prim_u_8_strict(deserializer);
    var var_data = sse_decode_list_prim_u_8_strict(deserializer);
    var var_stamp = sse_decode_list_prim_u_8_strict(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return VertexChunkData(
        index: var_index,
        address: var_address,
        data: var_data,
        stamp: var_stamp,
        error: var_error);
  }

  @protected
  VertexChunkDownload sse_decode_vertex_chunk_download(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_data = sse_decode_list_prim_u_8_strict(deserializer);
    var var_stamp = sse_decode_list_prim_u_8_strict(deserializer);
    var var_servedBy = sse_decode_String(deserializer);
    return VertexChunkDownload(
        data: var_data, stamp: var_stamp, servedBy: var_servedBy);
  }

  @protected
  VertexChunkUpload sse_decode_vertex_chunk_upload(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_address = sse_decode_list_prim_u_8_strict(deserializer);
    var var_data = sse_decode_list_prim_u_8_strict(deserializer);
    var var_stamp = sse_decode_list_prim_u_8_strict(deserializer);
    var var_validate = sse_decode_bool(deserializer);
    return VertexChunkUpload(
        address: var_address,
        data: var_data,
        stamp: var_stamp,
        validate: var_validate);
  }

  @protected
  VertexClientConfig sse_decode_vertex_client_config(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_network = sse_decode_vertex_network(deserializer);
    var var_privateKey = sse_decode_opt_list_prim_u_8_strict(deserializer);
    var var_bootnodes = sse_decode_list_String(deserializer);
    return VertexClientConfig(
        network: var_network,
        privateKey: var_privateKey,
        bootnodes: var_bootnodes);
  }

  @protected
  VertexNetwork sse_decode_vertex_network(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return VertexNetwork.values[inner];
  }

  @protected
  VertexPushReceipt sse_decode_vertex_push_receipt(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_storer = sse_decode_String(deserializer);
    var var_signature = sse_decode_list_prim_u_8_strict(deserializer);
    var var_nonce = sse_decode_list_prim_u_8_strict(deserializer);
    var var_storageRadius = sse_decode_u_32(deserializer);
    return VertexPushReceipt(
        storer: var_storer,
        signature: var_signature,
        nonce: var_nonce,
        storageRadius: var_storageRadius);
  }

  @protected
  VertexStreamConfig sse_decode_vertex_stream_config(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_windowBytes = sse_decode_u_64(deserializer);
    var var_maxConcurrency = sse_decode_u_32(deserializer);
    return VertexStreamConfig(
        windowBytes: var_windowBytes, maxConcurrency: var_maxConcurrency);
  }

  @protected
  VertexUploadAck sse_decode_vertex_upload_ack(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_index = sse_decode_u_64(deserializer);
    var var_address = sse_decode_list_prim_u_8_strict(deserializer);
    var var_receipt =
        sse_decode_opt_box_autoadd_vertex_push_receipt(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return VertexUploadAck(
        index: var_index,
        address: var_address,
        receipt: var_receipt,
        error: var_error);
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVertexClient(
          VertexClient self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as VertexClientImpl).frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVertexClient(
          VertexClient self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as VertexClientImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVertexClient(
          VertexClient self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as VertexClientImpl).frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void sse_encode_StreamSink_log_line_Sse(
      RustStreamSink<LogLine> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_log_line,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_StreamSink_vertex_chunk_data_Sse(
      RustStreamSink<VertexChunkData> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_vertex_chunk_data,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_StreamSink_vertex_upload_ack_Sse(
      RustStreamSink<VertexUploadAck> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_vertex_upload_ack,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_vertex_chunk_upload(
      VertexChunkUpload self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_vertex_chunk_upload(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_vertex_client_config(
      VertexClientConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_vertex_client_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_vertex_push_receipt(
      VertexPushReceipt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_vertex_push_receipt(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_vertex_stream_config(
      VertexStreamConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_vertex_stream_config(self, serializer);
  }

  @protected
  void sse_encode_counter_value(CounterValue self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_list_record_string_string(self.labels, serializer);
    sse_encode_u_64(self.value, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_ffi_error(FfiError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case FfiError_InvalidPrivateKey(len: final len):
        sse_encode_i_32(0, serializer);
        sse_encode_usize(len, serializer);
      case FfiError_InvalidAddress(len: final len):
        sse_encode_i_32(1, serializer);
        sse_encode_usize(len, serializer);
      case FfiError_InvalidStamp(reason: final reason):
        sse_encode_i_32(2, serializer);
        sse_encode_String(reason, serializer);
      case FfiError_ChunkMismatch(reason: final reason):
        sse_encode_i_32(3, serializer);
        sse_encode_String(reason, serializer);
      case FfiError_Build(reason: final reason):
        sse_encode_i_32(4, serializer);
        sse_encode_String(reason, serializer);
      case FfiError_Upload(reason: final reason):
        sse_encode_i_32(5, serializer);
        sse_encode_String(reason, serializer);
      case FfiError_Download(reason: final reason):
        sse_encode_i_32(6, serializer);
        sse_encode_String(reason, serializer);
      case FfiError_Logging(reason: final reason):
        sse_encode_i_32(7, serializer);
        sse_encode_String(reason, serializer);
      case FfiError_LoggingAlreadyInitialized():
        sse_encode_i_32(8, serializer);
      case FfiError_Metrics(reason: final reason):
        sse_encode_i_32(9, serializer);
        sse_encode_String(reason, serializer);
      case FfiError_MetricsAlreadyInitialized():
        sse_encode_i_32(10, serializer);
      case FfiError_MetricsNotInitialized():
        sse_encode_i_32(11, serializer);
    }
  }

  @protected
  void sse_encode_gauge_value(GaugeValue self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_list_record_string_string(self.labels, serializer);
    sse_encode_f_64(self.value, serializer);
  }

  @protected
  void sse_encode_histogram_value(
      HistogramValue self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_list_record_string_string(self.labels, serializer);
    sse_encode_u_64(self.count, serializer);
    sse_encode_f_64(self.sum, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_counter_value(
      List<CounterValue> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_counter_value(item, serializer);
    }
  }

  @protected
  void sse_encode_list_gauge_value(
      List<GaugeValue> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_gauge_value(item, serializer);
    }
  }

  @protected
  void sse_encode_list_histogram_value(
      List<HistogramValue> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_histogram_value(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_prim_u_8_strict(
      List<Uint8List> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_u_8_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_string(
      List<(String, String)> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_list_vertex_chunk_upload(
      List<VertexChunkUpload> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_vertex_chunk_upload(item, serializer);
    }
  }

  @protected
  void sse_encode_log_level(LogLevel self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_log_line(LogLine self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.timestampMs, serializer);
    sse_encode_log_level(self.level, serializer);
    sse_encode_String(self.target, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_list_record_string_string(self.fields, serializer);
  }

  @protected
  void sse_encode_metrics_snapshot(
      MetricsSnapshot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.timestampMs, serializer);
    sse_encode_list_counter_value(self.counters, serializer);
    sse_encode_list_gauge_value(self.gauges, serializer);
    sse_encode_list_histogram_value(self.histograms, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_vertex_push_receipt(
      VertexPushReceipt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_vertex_push_receipt(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
      Uint8List? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_record_string_string(
      (String, String) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_vertex_chunk_data(
      VertexChunkData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.index, serializer);
    sse_encode_list_prim_u_8_strict(self.address, serializer);
    sse_encode_list_prim_u_8_strict(self.data, serializer);
    sse_encode_list_prim_u_8_strict(self.stamp, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_vertex_chunk_download(
      VertexChunkDownload self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.data, serializer);
    sse_encode_list_prim_u_8_strict(self.stamp, serializer);
    sse_encode_String(self.servedBy, serializer);
  }

  @protected
  void sse_encode_vertex_chunk_upload(
      VertexChunkUpload self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.address, serializer);
    sse_encode_list_prim_u_8_strict(self.data, serializer);
    sse_encode_list_prim_u_8_strict(self.stamp, serializer);
    sse_encode_bool(self.validate, serializer);
  }

  @protected
  void sse_encode_vertex_client_config(
      VertexClientConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_vertex_network(self.network, serializer);
    sse_encode_opt_list_prim_u_8_strict(self.privateKey, serializer);
    sse_encode_list_String(self.bootnodes, serializer);
  }

  @protected
  void sse_encode_vertex_network(VertexNetwork self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_vertex_push_receipt(
      VertexPushReceipt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.storer, serializer);
    sse_encode_list_prim_u_8_strict(self.signature, serializer);
    sse_encode_list_prim_u_8_strict(self.nonce, serializer);
    sse_encode_u_32(self.storageRadius, serializer);
  }

  @protected
  void sse_encode_vertex_stream_config(
      VertexStreamConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.windowBytes, serializer);
    sse_encode_u_32(self.maxConcurrency, serializer);
  }

  @protected
  void sse_encode_vertex_upload_ack(
      VertexUploadAck self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.index, serializer);
    sse_encode_list_prim_u_8_strict(self.address, serializer);
    sse_encode_opt_box_autoadd_vertex_push_receipt(self.receipt, serializer);
    sse_encode_opt_String(self.error, serializer);
  }
}

@sealed
class VertexClientImpl extends RustOpaque implements VertexClient {
  // Not to be used by end users
  VertexClientImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  VertexClientImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_VertexClient,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_VertexClient,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_VertexClientPtr,
  );

  /// Download the chunk at `address` from the network.
  ///
  /// `address` is the chunk's 32-byte address. `verify_stamp` opts into postage
  /// stamp signer recovery; chunk content integrity is always enforced by the
  /// retrieval path.
  Future<VertexChunkDownload> downloadChunk(
          {required List<int> address, required bool verifyStamp}) =>
      RustLib.instance.api.crateApiClientVertexClientDownloadChunk(
          that: this, address: address, verifyStamp: verifyStamp);

  /// Stream-download a list of chunk addresses into `sink`.
  ///
  /// Drives the memory-bounded download pipeline: at most `config.window_bytes`
  /// of chunk payload is ever in flight, and the host receives each result as a
  /// [`VertexChunkData`] in request order. A per-address failure (a miss, wrong
  /// bytes, or no candidate peer) arrives as an item carrying `error`, never as
  /// a torn-down stream, so the host decides per address whether to continue.
  ///
  /// The bounded buffer lives in Rust: the pump pulls one stream item, copies
  /// its payload once into the boundary shape, and forwards it before pulling
  /// the next, so a host whose listener pauses transitively pauses the network
  /// reads. The returned [`FfiError`] only covers up-front input rejection
  /// (a malformed address); retrieval failures surface as stream items.
  ///
  /// Spawns the pump on the client's runtime and returns immediately; the
  /// stream completes when every address has produced an item.
  Stream<VertexChunkData> downloadStream(
          {required List<Uint8List> addresses,
          required VertexStreamConfig config}) =>
      RustLib.instance.api.crateApiClientVertexClientDownloadStream(
          that: this, addresses: addresses, config: config);

  /// Upload a pre-stamped chunk to the storers closest to its address.
  ///
  /// The chunk, its address, and its postage stamp are reconstructed into a
  /// strong [`StampedChunk`] before any network call. Returns the first
  /// storer's receipt.
  Future<VertexPushReceipt> uploadChunk({required VertexChunkUpload chunk}) =>
      RustLib.instance.api
          .crateApiClientVertexClientUploadChunk(that: this, chunk: chunk);

  /// Stream-upload a list of pre-stamped chunks, acking each into `sink`.
  ///
  /// The feed is the `chunks` list; the ack is the [`VertexUploadAck`] stream.
  /// The memory-bounded upload pipeline keeps at most `config.window_bytes` of
  /// payload in flight, admitting each chunk by its real encoded size, so a
  /// slow host that stops draining acks transitively pauses the network pushes
  /// and the heap stays flat regardless of how many chunks were fed.
  ///
  /// Each chunk is reconstructed into a strong [`StampedChunk`] before any
  /// network call; a chunk whose bytes do not match its address is rejected
  /// up front as an [`FfiError`] and no upload starts. Per-chunk push failures
  /// (no storer, rejection) surface as ack items carrying `error`.
  Stream<VertexUploadAck> uploadStream(
          {required List<VertexChunkUpload> chunks,
          required VertexStreamConfig config}) =>
      RustLib.instance.api.crateApiClientVertexClientUploadStream(
          that: this, chunks: chunks, config: config);
}
