// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/client.dart';
import 'api/error.dart';
import 'api/logging.dart';
import 'api/metrics.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_VertexClientPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVertexClient;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  VertexClient
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVertexClient(
          dynamic raw);

  @protected
  VertexClient
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVertexClient(
          dynamic raw);

  @protected
  VertexClient
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVertexClient(
          dynamic raw);

  @protected
  RustStreamSink<LogLine> dco_decode_StreamSink_log_line_Sse(dynamic raw);

  @protected
  RustStreamSink<VertexChunkData> dco_decode_StreamSink_vertex_chunk_data_Sse(
      dynamic raw);

  @protected
  RustStreamSink<VertexUploadAck> dco_decode_StreamSink_vertex_upload_ack_Sse(
      dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  VertexChunkUpload dco_decode_box_autoadd_vertex_chunk_upload(dynamic raw);

  @protected
  VertexClientConfig dco_decode_box_autoadd_vertex_client_config(dynamic raw);

  @protected
  VertexPushReceipt dco_decode_box_autoadd_vertex_push_receipt(dynamic raw);

  @protected
  VertexStreamConfig dco_decode_box_autoadd_vertex_stream_config(dynamic raw);

  @protected
  CounterValue dco_decode_counter_value(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FfiError dco_decode_ffi_error(dynamic raw);

  @protected
  GaugeValue dco_decode_gauge_value(dynamic raw);

  @protected
  HistogramValue dco_decode_histogram_value(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<CounterValue> dco_decode_list_counter_value(dynamic raw);

  @protected
  List<GaugeValue> dco_decode_list_gauge_value(dynamic raw);

  @protected
  List<HistogramValue> dco_decode_list_histogram_value(dynamic raw);

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<VertexChunkUpload> dco_decode_list_vertex_chunk_upload(dynamic raw);

  @protected
  LogLevel dco_decode_log_level(dynamic raw);

  @protected
  LogLine dco_decode_log_line(dynamic raw);

  @protected
  MetricsSnapshot dco_decode_metrics_snapshot(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  VertexPushReceipt? dco_decode_opt_box_autoadd_vertex_push_receipt(
      dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  VertexChunkData dco_decode_vertex_chunk_data(dynamic raw);

  @protected
  VertexChunkDownload dco_decode_vertex_chunk_download(dynamic raw);

  @protected
  VertexChunkUpload dco_decode_vertex_chunk_upload(dynamic raw);

  @protected
  VertexClientConfig dco_decode_vertex_client_config(dynamic raw);

  @protected
  VertexNetwork dco_decode_vertex_network(dynamic raw);

  @protected
  VertexPushReceipt dco_decode_vertex_push_receipt(dynamic raw);

  @protected
  VertexStreamConfig dco_decode_vertex_stream_config(dynamic raw);

  @protected
  VertexUploadAck dco_decode_vertex_upload_ack(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  VertexClient
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVertexClient(
          SseDeserializer deserializer);

  @protected
  VertexClient
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVertexClient(
          SseDeserializer deserializer);

  @protected
  VertexClient
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVertexClient(
          SseDeserializer deserializer);

  @protected
  RustStreamSink<LogLine> sse_decode_StreamSink_log_line_Sse(
      SseDeserializer deserializer);

  @protected
  RustStreamSink<VertexChunkData> sse_decode_StreamSink_vertex_chunk_data_Sse(
      SseDeserializer deserializer);

  @protected
  RustStreamSink<VertexUploadAck> sse_decode_StreamSink_vertex_upload_ack_Sse(
      SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  VertexChunkUpload sse_decode_box_autoadd_vertex_chunk_upload(
      SseDeserializer deserializer);

  @protected
  VertexClientConfig sse_decode_box_autoadd_vertex_client_config(
      SseDeserializer deserializer);

  @protected
  VertexPushReceipt sse_decode_box_autoadd_vertex_push_receipt(
      SseDeserializer deserializer);

  @protected
  VertexStreamConfig sse_decode_box_autoadd_vertex_stream_config(
      SseDeserializer deserializer);

  @protected
  CounterValue sse_decode_counter_value(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FfiError sse_decode_ffi_error(SseDeserializer deserializer);

  @protected
  GaugeValue sse_decode_gauge_value(SseDeserializer deserializer);

  @protected
  HistogramValue sse_decode_histogram_value(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<CounterValue> sse_decode_list_counter_value(
      SseDeserializer deserializer);

  @protected
  List<GaugeValue> sse_decode_list_gauge_value(SseDeserializer deserializer);

  @protected
  List<HistogramValue> sse_decode_list_histogram_value(
      SseDeserializer deserializer);

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
      SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
      SseDeserializer deserializer);

  @protected
  List<VertexChunkUpload> sse_decode_list_vertex_chunk_upload(
      SseDeserializer deserializer);

  @protected
  LogLevel sse_decode_log_level(SseDeserializer deserializer);

  @protected
  LogLine sse_decode_log_line(SseDeserializer deserializer);

  @protected
  MetricsSnapshot sse_decode_metrics_snapshot(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  VertexPushReceipt? sse_decode_opt_box_autoadd_vertex_push_receipt(
      SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  (String, String) sse_decode_record_string_string(
      SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  VertexChunkData sse_decode_vertex_chunk_data(SseDeserializer deserializer);

  @protected
  VertexChunkDownload sse_decode_vertex_chunk_download(
      SseDeserializer deserializer);

  @protected
  VertexChunkUpload sse_decode_vertex_chunk_upload(
      SseDeserializer deserializer);

  @protected
  VertexClientConfig sse_decode_vertex_client_config(
      SseDeserializer deserializer);

  @protected
  VertexNetwork sse_decode_vertex_network(SseDeserializer deserializer);

  @protected
  VertexPushReceipt sse_decode_vertex_push_receipt(
      SseDeserializer deserializer);

  @protected
  VertexStreamConfig sse_decode_vertex_stream_config(
      SseDeserializer deserializer);

  @protected
  VertexUploadAck sse_decode_vertex_upload_ack(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVertexClient(
          VertexClient self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVertexClient(
          VertexClient self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVertexClient(
          VertexClient self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_log_line_Sse(
      RustStreamSink<LogLine> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_vertex_chunk_data_Sse(
      RustStreamSink<VertexChunkData> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_vertex_upload_ack_Sse(
      RustStreamSink<VertexUploadAck> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_vertex_chunk_upload(
      VertexChunkUpload self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_vertex_client_config(
      VertexClientConfig self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_vertex_push_receipt(
      VertexPushReceipt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_vertex_stream_config(
      VertexStreamConfig self, SseSerializer serializer);

  @protected
  void sse_encode_counter_value(CounterValue self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_error(FfiError self, SseSerializer serializer);

  @protected
  void sse_encode_gauge_value(GaugeValue self, SseSerializer serializer);

  @protected
  void sse_encode_histogram_value(
      HistogramValue self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_counter_value(
      List<CounterValue> self, SseSerializer serializer);

  @protected
  void sse_encode_list_gauge_value(
      List<GaugeValue> self, SseSerializer serializer);

  @protected
  void sse_encode_list_histogram_value(
      List<HistogramValue> self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_prim_u_8_strict(
      List<Uint8List> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_string(
      List<(String, String)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_vertex_chunk_upload(
      List<VertexChunkUpload> self, SseSerializer serializer);

  @protected
  void sse_encode_log_level(LogLevel self, SseSerializer serializer);

  @protected
  void sse_encode_log_line(LogLine self, SseSerializer serializer);

  @protected
  void sse_encode_metrics_snapshot(
      MetricsSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_vertex_push_receipt(
      VertexPushReceipt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
      Uint8List? self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_string(
      (String, String) self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_vertex_chunk_data(
      VertexChunkData self, SseSerializer serializer);

  @protected
  void sse_encode_vertex_chunk_download(
      VertexChunkDownload self, SseSerializer serializer);

  @protected
  void sse_encode_vertex_chunk_upload(
      VertexChunkUpload self, SseSerializer serializer);

  @protected
  void sse_encode_vertex_client_config(
      VertexClientConfig self, SseSerializer serializer);

  @protected
  void sse_encode_vertex_network(VertexNetwork self, SseSerializer serializer);

  @protected
  void sse_encode_vertex_push_receipt(
      VertexPushReceipt self, SseSerializer serializer);

  @protected
  void sse_encode_vertex_stream_config(
      VertexStreamConfig self, SseSerializer serializer);

  @protected
  void sse_encode_vertex_upload_ack(
      VertexUploadAck self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVertexClient(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVertexClient(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVertexClient(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVertexClient(
              ptr);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVertexClient(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVertexClient(
          int ptr);
}
