// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `build_identity`, `build_network`, `chunks_from`, `network_spec`, `new`, `parse_address`, `parse_stamp`, `receipt_into_ffi`, `reconstruct_upload`, `stream_config`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `LaunchContext`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `data_dir`, `drop`, `executor`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VertexClient>>
abstract class VertexClient implements RustOpaqueInterface {
  /// Build and start an embedded client for `config`.
  ///
  /// Spins up a native multi-thread runtime, constructs the client node on it,
  /// and spawns the node's event loop as a background task. Returns once the
  /// node is built and running; the client begins discovering peers
  /// immediately.
  ///
  /// One client per process. The node internals resolve their task executor
  /// from a process-global slot that the first built client populates, so a
  /// second concurrent client would spawn its node tasks onto the first
  /// client's runtime. Build a single client, hold it for the process
  /// lifetime, and drop it to shut the node down.
  static Future<VertexClient> build({required VertexClientConfig config}) =>
      RustLib.instance.api.crateApiClientVertexClientBuild(config: config);

  /// Download the chunk at `address` from the network.
  ///
  /// `address` is the chunk's 32-byte address. `verify_stamp` opts into postage
  /// stamp signer recovery; chunk content integrity is always enforced by the
  /// retrieval path.
  Future<VertexChunkDownload> downloadChunk(
      {required List<int> address, required bool verifyStamp});

  /// Stream-download a list of chunk addresses into `sink`.
  ///
  /// Drives the memory-bounded download pipeline: at most `config.window_bytes`
  /// of chunk payload is ever in flight, and the host receives each result as a
  /// [`VertexChunkData`] in request order. A per-address failure (a miss, wrong
  /// bytes, or no candidate peer) arrives as an item carrying `error`, never as
  /// a torn-down stream, so the host decides per address whether to continue.
  ///
  /// The bounded buffer lives in Rust: the pump pulls one stream item, copies
  /// its payload once into the boundary shape, and forwards it before pulling
  /// the next, so a host whose listener pauses transitively pauses the network
  /// reads. The returned [`FfiError`] only covers up-front input rejection
  /// (a malformed address); retrieval failures surface as stream items.
  ///
  /// Spawns the pump on the client's runtime and returns immediately; the
  /// stream completes when every address has produced an item.
  Stream<VertexChunkData> downloadStream(
      {required List<Uint8List> addresses, required VertexStreamConfig config});

  /// Upload a pre-stamped chunk to the storers closest to its address.
  ///
  /// The chunk, its address, and its postage stamp are reconstructed into a
  /// strong [`StampedChunk`] before any network call. Returns the first
  /// storer's receipt.
  Future<VertexPushReceipt> uploadChunk({required VertexChunkUpload chunk});

  /// Stream-upload a list of pre-stamped chunks, acking each into `sink`.
  ///
  /// The feed is the `chunks` list; the ack is the [`VertexUploadAck`] stream.
  /// The memory-bounded upload pipeline keeps at most `config.window_bytes` of
  /// payload in flight, admitting each chunk by its real encoded size, so a
  /// slow host that stops draining acks transitively pauses the network pushes
  /// and the heap stays flat regardless of how many chunks were fed.
  ///
  /// Each chunk is reconstructed into a strong [`StampedChunk`] before any
  /// network call; a chunk whose bytes do not match its address is rejected
  /// up front as an [`FfiError`] and no upload starts. Per-chunk push failures
  /// (no storer, rejection) surface as ack items carrying `error`.
  Stream<VertexUploadAck> uploadStream(
      {required List<VertexChunkUpload> chunks,
      required VertexStreamConfig config});
}
