// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `from`, `from`

@freezed
sealed class FfiError with _$FfiError implements FrbException {
  const FfiError._();

  /// The supplied private key was not a 32-byte value.
  const factory FfiError.invalidPrivateKey({
    /// Length of the rejected key in bytes.
    required BigInt len,
  }) = FfiError_InvalidPrivateKey;

  /// The supplied chunk address was not a 32-byte value.
  const factory FfiError.invalidAddress({
    /// Length of the rejected address in bytes.
    required BigInt len,
  }) = FfiError_InvalidAddress;

  /// The postage stamp bytes did not decode to a valid stamp.
  const factory FfiError.invalidStamp({
    /// Why the stamp failed to decode.
    required String reason,
  }) = FfiError_InvalidStamp;

  /// The chunk bytes did not reconstruct to the supplied address.
  const factory FfiError.chunkMismatch({
    /// Why reconstruction failed.
    required String reason,
  }) = FfiError_ChunkMismatch;

  /// Building the embedded client node failed.
  const factory FfiError.build({
    /// Why the build failed.
    required String reason,
  }) = FfiError_Build;

  /// A network upload failed.
  const factory FfiError.upload({
    /// Why the upload failed.
    required String reason,
  }) = FfiError_Upload;

  /// A network download failed.
  const factory FfiError.download({
    /// Why the download failed.
    required String reason,
  }) = FfiError_Download;

  /// Installing the logging subscriber failed.
  const factory FfiError.logging({
    /// Why logging setup failed (an unparseable filter or a subscriber that
    /// could not be installed).
    required String reason,
  }) = FfiError_Logging;

  /// Logging was already initialized for this process.
  ///
  /// A process has exactly one global tracing subscriber, so the first
  /// `init_logging` call wins and a later call is rejected without disturbing
  /// the installed subscriber.
  const factory FfiError.loggingAlreadyInitialized() =
      FfiError_LoggingAlreadyInitialized;

  /// Installing the metrics recorder failed.
  const factory FfiError.metrics({
    /// Why metrics setup failed (typically a recorder installed by other
    /// means already occupying the process-global slot).
    required String reason,
  }) = FfiError_Metrics;

  /// Metrics were already initialized for this process.
  ///
  /// A process has exactly one global metrics recorder, so the first
  /// `init_metrics` call wins and a later call is rejected without
  /// disturbing the installed recorder.
  const factory FfiError.metricsAlreadyInitialized() =
      FfiError_MetricsAlreadyInitialized;

  /// A metrics snapshot was requested before `init_metrics` ran.
  const factory FfiError.metricsNotInitialized() =
      FfiError_MetricsNotInitialized;
}
