// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `line_from_event`, `now_ms`, `record`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `LogVisitor`, `StreamLayer`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `from`, `on_event`, `record_debug`, `record_str`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

/// Initialize logging for the embedded client.
///
/// Installs a process-global tracing subscriber that filters events by `level`
/// and forwards each surviving event to `sink` as a typed [`LogLine`]. `level`
/// is an `EnvFilter`-style directive: a bare level (`"info"`, `"debug"`) sets
/// the global maximum, and per-target directives (`"info,vertex_topology=debug"`)
/// tune individual modules. An unparseable directive is rejected.
///
/// Call once, before or just after [`super::client::VertexClient::build`]. A
/// second call returns [`FfiError::LoggingAlreadyInitialized`] without
/// disturbing the installed subscriber: `tracing` permits one global subscriber
/// per process.
///
/// To compile logging out entirely, a host sets a `tracing` `release_max_level_*`
/// feature in its own `Cargo.toml`; cargo feature unification then strips the
/// filtered events at compile time and `init_logging` forwards nothing below the
/// chosen level.
Stream<LogLine> initLogging({required String level}) =>
    RustLib.instance.api.crateApiLoggingInitLogging(level: level);

/// Severity of a forwarded log event.
///
/// A typed mirror of `tracing`'s levels so the host matches on an enum instead
/// of parsing a string.
enum LogLevel {
  /// Most verbose: fine-grained developer tracing.
  trace,

  /// Developer-facing detail.
  debug,

  /// Operator-facing state changes.
  info,

  /// Operator-facing, informational but noteworthy.
  warn,

  /// Operator-facing, requires attention.
  error,
  ;
}

/// A single structured log event crossing the FFI boundary.
///
/// Plain data only: every field is a primitive or a string so the bindings
/// expose it to any host without a serde backend. `fields` carries the event's
/// key-value pairs flattened to strings, with the special `message` field
/// hoisted out into [`LogLine::message`].
class LogLine {
  /// Event time in milliseconds since the Unix epoch.
  final PlatformInt64 timestampMs;

  /// Severity of the event.
  final LogLevel level;

  /// The event's target (typically the emitting module path).
  final String target;

  /// The event's primary message.
  final String message;

  /// Flattened key-value fields captured from the event, message excluded.
  final List<(String, String)> fields;

  const LogLine({
    required this.timestampMs,
    required this.level,
    required this.target,
    required this.message,
    required this.fields,
  });

  @override
  int get hashCode =>
      timestampMs.hashCode ^
      level.hashCode ^
      target.hashCode ^
      message.hashCode ^
      fields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LogLine &&
          runtimeType == other.runtimeType &&
          timestampMs == other.timestampMs &&
          level == other.level &&
          target == other.target &&
          message == other.message &&
          fields == other.fields;
}
