// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `count`, `name_and_labels`, `snapshot_from`, `sum`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `HistogramSummary`, `SnapshotRecorder`, `SummaryStorage`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `counter`, `describe_counter`, `describe_gauge`, `describe_histogram`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `gauge`, `histogram`, `record`, `register_counter`, `register_gauge`, `register_histogram`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

/// Initialize metrics collection for the embedded client.
///
/// Installs a process-global recorder that accumulates every counter, gauge,
/// and histogram the node records, for [`metrics_snapshot`] to read back on
/// demand. Call once, before [`super::client::VertexClient::build`], so
/// activity from the first dial onward is captured.
///
/// Single-shot: `metrics` permits one global recorder per process, so a second
/// call returns [`FfiError::MetricsAlreadyInitialized`] without disturbing the
/// installed recorder.
Future<void> initMetrics() => RustLib.instance.api.crateApiMetricsInitMetrics();

/// Read the current value of every metric the node has recorded.
///
/// Returns a point-in-time [`MetricsSnapshot`]; requires a prior
/// [`init_metrics`] call, otherwise [`FfiError::MetricsNotInitialized`].
///
/// Each call walks every registered series and allocates the returned vectors,
/// so it is cheap but not free. Poll on demand (every 1 to 5 seconds while a
/// diagnostics view is visible), stop when the data is not being looked at,
/// and never poll from a background task on a mobile host.
Future<MetricsSnapshot> metricsSnapshot() =>
    RustLib.instance.api.crateApiMetricsMetricsSnapshot();

/// A counter's current value.
///
/// Plain data only: the metric name, its label pairs, and the monotonic count.
class CounterValue {
  /// Metric name, for example `topology_connections_total`.
  final String name;

  /// Label key-value pairs identifying the series.
  final List<(String, String)> labels;

  /// Monotonically increasing count since [`init_metrics`].
  final BigInt value;

  const CounterValue({
    required this.name,
    required this.labels,
    required this.value,
  });

  @override
  int get hashCode => name.hashCode ^ labels.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CounterValue &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          labels == other.labels &&
          value == other.value;
}

/// A gauge's current value.
class GaugeValue {
  /// Metric name, for example `topology_connected_peers`.
  final String name;

  /// Label key-value pairs identifying the series.
  final List<(String, String)> labels;

  /// The gauge's current value.
  final double value;

  const GaugeValue({
    required this.name,
    required this.labels,
    required this.value,
  });

  @override
  int get hashCode => name.hashCode ^ labels.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GaugeValue &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          labels == other.labels &&
          value == other.value;
}

/// A histogram's bounded running summary.
///
/// The count and sum since [`init_metrics`]: the delta between two snapshots
/// yields a rate and an interval average. Quantiles are deliberately absent;
/// see the module docs.
class HistogramValue {
  /// Metric name, for example `topology_dial_duration_seconds`.
  final String name;

  /// Label key-value pairs identifying the series.
  final List<(String, String)> labels;

  /// Number of observations recorded.
  final BigInt count;

  /// Sum of all observed values.
  final double sum;

  const HistogramValue({
    required this.name,
    required this.labels,
    required this.count,
    required this.sum,
  });

  @override
  int get hashCode =>
      name.hashCode ^ labels.hashCode ^ count.hashCode ^ sum.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistogramValue &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          labels == other.labels &&
          count == other.count &&
          sum == other.sum;
}

/// A point-in-time view of every metric the node has recorded.
///
/// Entries are sorted by name then labels, so consecutive snapshots line up
/// for delta computation and a diagnostics view renders in a stable order.
class MetricsSnapshot {
  /// Snapshot time in milliseconds since the Unix epoch.
  final PlatformInt64 timestampMs;

  /// All counters, sorted.
  final List<CounterValue> counters;

  /// All gauges, sorted.
  final List<GaugeValue> gauges;

  /// All histogram summaries, sorted.
  final List<HistogramValue> histograms;

  const MetricsSnapshot({
    required this.timestampMs,
    required this.counters,
    required this.gauges,
    required this.histograms,
  });

  @override
  int get hashCode =>
      timestampMs.hashCode ^
      counters.hashCode ^
      gauges.hashCode ^
      histograms.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MetricsSnapshot &&
          runtimeType == other.runtimeType &&
          timestampMs == other.timestampMs &&
          counters == other.counters &&
          gauges == other.gauges &&
          histograms == other.histograms;
}
