// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// One item in a streaming download: either a verified chunk or a per-address
/// failure.
///
/// The download stream yields exactly one of these per requested address, in
/// request order. A failed retrieval (peer miss, wrong bytes, no candidates)
/// arrives as an item with `error` set and `data` empty, so a host can decide
/// per address whether to abort or skip without tearing down the whole stream.
/// The payload is copied once here, at the boundary: inside Rust the chunk stays
/// `Bytes`.
class VertexChunkData {
  /// Zero-based position of this item in the requested address list.
  final BigInt index;

  /// The chunk's 32-byte address.
  final Uint8List address;

  /// The chunk's wire-encoded bytes (span plus payload). Empty when `error`
  /// is set.
  final Uint8List data;

  /// The chunk's 113-byte postage stamp. Empty when `error` is set.
  final Uint8List stamp;

  /// A failure message when this address could not be served, otherwise
  /// `None`.
  final String? error;

  const VertexChunkData({
    required this.index,
    required this.address,
    required this.data,
    required this.stamp,
    this.error,
  });

  @override
  int get hashCode =>
      index.hashCode ^
      address.hashCode ^
      data.hashCode ^
      stamp.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VertexChunkData &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          address == other.address &&
          data == other.data &&
          stamp == other.stamp &&
          error == other.error;
}

/// A downloaded chunk and its postage stamp.
class VertexChunkDownload {
  /// The chunk's wire-encoded bytes (span plus payload).
  final Uint8List data;

  /// The chunk's 113-byte postage stamp.
  final Uint8List stamp;

  /// Overlay address of the peer that served the chunk, hex-encoded.
  final String servedBy;

  const VertexChunkDownload({
    required this.data,
    required this.stamp,
    required this.servedBy,
  });

  @override
  int get hashCode => data.hashCode ^ stamp.hashCode ^ servedBy.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VertexChunkDownload &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          stamp == other.stamp &&
          servedBy == other.servedBy;
}

/// A pre-stamped chunk to upload.
///
/// `address` and `stamp` are the chunk's 32-byte address and its 113-byte wire
/// stamp. `data` is the chunk's wire encoding (span plus payload). The chunk type
/// is inferred from `data` and `address` during reconstruction, so the host does
/// not pass it separately: an address that does not match the bytes is rejected.
class VertexChunkUpload {
  /// The chunk's 32-byte address.
  final Uint8List address;

  /// The chunk's wire-encoded bytes (span plus payload).
  final Uint8List data;

  /// The chunk's 113-byte postage stamp.
  final Uint8List stamp;

  /// When true, the stamp signature is recovered before the chunk is pushed.
  /// When false, the chunk is pushed without stamp validation.
  final bool validate;

  const VertexChunkUpload({
    required this.address,
    required this.data,
    required this.stamp,
    required this.validate,
  });

  @override
  int get hashCode =>
      address.hashCode ^ data.hashCode ^ stamp.hashCode ^ validate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VertexChunkUpload &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          data == other.data &&
          stamp == other.stamp &&
          validate == other.validate;
}

/// Configuration for building an embedded client.
///
/// The host supplies an optional signing key and the target network. An absent
/// key yields a random ephemeral identity, which is appropriate for a short
/// lived client that only uploads and downloads.
class VertexClientConfig {
  /// The network to join.
  final VertexNetwork network;

  /// Optional 32-byte secp256k1 private key. When `None`, the client runs with
  /// a random ephemeral identity.
  final Uint8List? privateKey;

  /// Optional multiaddrs of bootnodes to dial on startup. When empty, the
  /// network spec's defaults are used.
  final List<String> bootnodes;

  const VertexClientConfig({
    required this.network,
    this.privateKey,
    required this.bootnodes,
  });

  static Future<VertexClientConfig> default_() =>
      RustLib.instance.api.crateApiTypesVertexClientConfigDefault();

  @override
  int get hashCode =>
      network.hashCode ^ privateKey.hashCode ^ bootnodes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VertexClientConfig &&
          runtimeType == other.runtimeType &&
          network == other.network &&
          privateKey == other.privateKey &&
          bootnodes == other.bootnodes;
}

/// Which network the embedded client joins.
enum VertexNetwork {
  /// The Swarm mainnet.
  mainnet,

  /// The Swarm testnet.
  testnet,

  /// An isolated development network.
  dev,
  ;

  static Future<VertexNetwork> default_() =>
      RustLib.instance.api.crateApiTypesVertexNetworkDefault();
}

/// Proof that a storer accepted an uploaded chunk.
class VertexPushReceipt {
  /// Overlay address of the accepting storer, hex-encoded.
  final String storer;

  /// The storer's signature over the receipt (65 bytes).
  final Uint8List signature;

  /// The nonce the storer used when signing (32 bytes).
  final Uint8List nonce;

  /// The storer's storage radius at the time of acceptance.
  final int storageRadius;

  const VertexPushReceipt({
    required this.storer,
    required this.signature,
    required this.nonce,
    required this.storageRadius,
  });

  @override
  int get hashCode =>
      storer.hashCode ^
      signature.hashCode ^
      nonce.hashCode ^
      storageRadius.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VertexPushReceipt &&
          runtimeType == other.runtimeType &&
          storer == other.storer &&
          signature == other.signature &&
          nonce == other.nonce &&
          storageRadius == other.storageRadius;
}

/// Tuning for a streaming download or upload.
///
/// `window_bytes` is the memory ceiling on outstanding payload, expressed in
/// bytes so the host sizes it against a real budget. `max_concurrency` caps
/// simultaneous in-flight requests on top of the byte window. Both are clamped
/// to at least one inside Rust, so a zero never deadlocks the stream.
class VertexStreamConfig {
  /// Soft byte ceiling on outstanding in-flight payload.
  final BigInt windowBytes;

  /// Hard cap on simultaneous in-flight requests.
  final int maxConcurrency;

  const VertexStreamConfig({
    required this.windowBytes,
    required this.maxConcurrency,
  });

  @override
  int get hashCode => windowBytes.hashCode ^ maxConcurrency.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VertexStreamConfig &&
          runtimeType == other.runtimeType &&
          windowBytes == other.windowBytes &&
          maxConcurrency == other.maxConcurrency;
}

/// One acknowledgement in a streaming upload.
///
/// The upload stream yields exactly one of these per fed chunk, in feed order.
/// A successful push carries the storer's receipt; a failure carries `error` and
/// a default receipt. Rust owns the bounded in-flight window, so feeding a long
/// list never grows the heap past the configured byte budget: a slow host that
/// stops draining acks transitively pauses the network pushes.
class VertexUploadAck {
  /// Zero-based position of this ack in the fed chunk list.
  final BigInt index;

  /// The chunk's 32-byte address.
  final Uint8List address;

  /// The storer's receipt for a successful push. `None` when `error` is set.
  final VertexPushReceipt? receipt;

  /// A failure message when the chunk could not be stored, otherwise `None`.
  final String? error;

  const VertexUploadAck({
    required this.index,
    required this.address,
    this.receipt,
    this.error,
  });

  @override
  int get hashCode =>
      index.hashCode ^ address.hashCode ^ receipt.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VertexUploadAck &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          address == other.address &&
          receipt == other.receipt &&
          error == other.error;
}
